---

jobs:
- name: test-task
  plan:
  - get: github
    trigger: true
  - task: commit
    file: github/task.yml

resources:
- name: github
  type: git
  source:
    uri: https://github.com/EngineerBetter/cf-openstack-validator.git
    branch: master